# Generated by Django 6.0.4 on 2026-06-03 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('cursor', 'Cursor'), ('canvas', 'Canvas')], max_length=10)),
                ('item_id', models.UUIDField()),
                ('price_paid', models.PositiveIntegerField()),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-bought_at'],
            },
        ),
    ]
