# Generated by Django 6.0.4 on 2026-06-03 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='canvases',
            field=models.ManyToManyField(blank=True, related_name='inventories', to='users.canvas'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cursors',
            field=models.ManyToManyField(blank=True, related_name='inventories', to='users.cursor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
