# Generated by Django 6.0.4 on 2026-06-03 08:31

import game.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(default=game.models.generate_game_number, editable=False, max_length=6, unique=True)),
                ('max_players', models.PositiveIntegerField(default=8)),
                ('started', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('prompt', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rounds',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('coins_earned', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
