# Generated by Django 6.0.6 on 2026-06-08 07:54

import django.core.validators
import game.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(2, message='Минимум 2 игрока.'), django.core.validators.MaxValueValidator(8, message='Максимум 8 игроков.')]),
        ),
        migrations.AlterField(
            model_name='round',
            name='prompt',
            field=models.CharField(max_length=100, validators=[game.validators.validate_prompt]),
        ),
        migrations.AlterField(
            model_name='score',
            name='coins_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.TextField(max_length=100),
        ),
    ]
