# Generated by Django 6.0.6 on 2026-06-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_max_players_alter_round_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
    ]
