# Generated by Django 6.0.6 on 2026-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
