export interface DebuffInfo {
  name: string;
  description: string;
  rarity: "COMMON" | "RARE" | "EPIC" | "MYTHIC" | "LEGENDARY";
}

export const DEBUFF_MAP: Record<string, DebuffInfo> = {
  chill:        { name: "Chill",        rarity: "COMMON",    description: "Замедляет скорость движения курсора на 20%" },
  blur:         { name: "Blur",         rarity: "COMMON",    description: "Слегка размывает интерфейс холста" },
  fog:          { name: "Fog",          rarity: "COMMON",    description: "Во весь экран появляется туман" },
  smudge:       { name: "Smudge",       rarity: "COMMON",    description: "Закрывает центр экрана чернильной кляксой" },
  weight:       { name: "Weight",       rarity: "COMMON",    description: "Увеличивает инерцию курсора — медленнее разгоняется и останавливается" },
  static:       { name: "Static",       rarity: "COMMON",    description: "По экрану холста начинают идти мелкие серые полосы" },
  carousel:     { name: "Carousel",     rarity: "COMMON",    description: "Холст начинает медленно вращаться" },
  flash:        { name: "Flash",        rarity: "COMMON",    description: "Ослепляет холст белой вспышкой" },
  eraser:       { name: "Eraser",       rarity: "COMMON",    description: "Появляется маленький ластик, который нельзя убрать с холста" },
  anonim:       { name: "Anonim",       rarity: "COMMON",    description: "Игрок видит всех одинаковыми" },
  mirror:       { name: "Mirror",       rarity: "COMMON",    description: "Отражает дебафф на самого себя" },
  advertising:  { name: "Advertising",  rarity: "COMMON",    description: "Всплывает много рекламы" },
  palette:      { name: "Palette",      rarity: "COMMON",    description: "Курсор переключился на другой цвет" },
  captcha:      { name: "Captcha",      rarity: "COMMON",    description: "Необходимо решить капчу" },
  darkness:     { name: "Darkness",     rarity: "COMMON",    description: "Рисуй в темноте" },
  collapse:     { name: "Collapse",     rarity: "RARE",      description: "Все элементы интерфейса падают" },
  vandal:       { name: "Vandal",       rarity: "RARE",      description: "Игрок начинает бить по своему холсту как стекло" },
  shake:        { name: "Shake",        rarity: "RARE",      description: "Экран слегка дрожит и трясётся" },
  zoom:         { name: "Zoom",         rarity: "RARE",      description: "Камера резко увеличивается за курсором" },
  quickly:      { name: "Quickly",      rarity: "RARE",      description: "Скорость курсора увеличивается на 20%" },
  popup:        { name: "Popup",        rarity: "RARE",      description: "Всплывает фейк-окно, которое нужно закрыть" },
  timer:        { name: "Timer",        rarity: "RARE",      description: "Таймер резко начинает ускоряться (только визуально)" },
  palette_swap: { name: "Palette Swap", rarity: "RARE",      description: "У палитры резко меняются цвета" },
  blocking:     { name: "Blocking",     rarity: "RARE",      description: "Холст блокируется якобы ошибкой" },
  freeze:       { name: "Freeze",       rarity: "RARE",      description: "Курсор замирает" },
  riddle:       { name: "Riddle",       rarity: "EPIC",      description: "Появляется загадка, необходимо ввести правильный ответ" },
  puzzle:       { name: "Puzzle",       rarity: "EPIC",      description: "На месте рисунка появляется маленькая пазл-головоломка" },
  quiz:         { name: "Quiz",         rarity: "EPIC",      description: "Появляется вопрос с вариантами ответа, нужно выбрать правильный" },
  code:         { name: "Code",         rarity: "EPIC",      description: "На экране показывается код, который необходимо ввести в поле" },
  maze:         { name: "Maze",         rarity: "EPIC",      description: "Необходимо провести курсор через мини-лабиринт" },
  agreement:    { name: "Agreement",    rarity: "EPIC",      description: "Появляется всплывающее соглашение, которое нужно прочитать и нажать «Принять»" },
  survey:       { name: "Survey",       rarity: "EPIC",      description: "Короткий опрос из одного вопроса блокирует экран" },
  password:     { name: "Password",     rarity: "EPIC",      description: "Необходимо ввести пароль, который появляется на экране на секунду" },
  scan:         { name: "Scan",         rarity: "EPIC",      description: "Фейковая проверка безопасности с прогресс-баром, нужно дождаться окончания" },
  verify:       { name: "Verify",       rarity: "EPIC",      description: "Необходимо кликнуть на серию правильных элементов как в капче" },
  siren:        { name: "Siren",        rarity: "MYTHIC",    description: "Громкая сирена" },
  hiss:         { name: "Hiss",         rarity: "MYTHIC",    description: "Постоянный шум помех в динамиках" },
  echo:         { name: "Echo",         rarity: "MYTHIC",    description: "Все звуки интерфейса начинают звучать с эхом" },
  pyhindu:      { name: "PyHindu",      rarity: "MYTHIC",    description: "Вынуждает заново пройти капчу Индуса" },
  ringtone:     { name: "Ringtone",     rarity: "MYTHIC",    description: "Громкая фейковая мелодия звонка" },
  whisper:      { name: "Whisper",      rarity: "MYTHIC",    description: "Тихий нарастающий шёпот на фоне" },
  glitch:       { name: "Glitch",       rarity: "MYTHIC",    description: "Звуки интерфейса начинают заикаться и искажаться" },
  storm:        { name: "Storm",        rarity: "MYTHIC",    description: "Звуки плохой погоды: ветер, дождь и гром" },
  zombie:       { name: "Zombie",       rarity: "MYTHIC",    description: "Звуки зомби" },
  bombs:        { name: "Bombs",        rarity: "MYTHIC",    description: "Звуки взрывов" },
  questions:    { name: "Questions",    rarity: "LEGENDARY", description: "Игрок на фоне отвечает на вопросы, иначе окна будут становиться всё больше" },
  exam:         { name: "Exam",         rarity: "LEGENDARY", description: "Игрок вынужден отвечать на вопросы, увеличивая размер холста" },
  weighting:    { name: "Weighting",    rarity: "LEGENDARY", description: "Курсор станет тяжелее" },
  weapons:      { name: "Weapons",      rarity: "LEGENDARY", description: "Игрок крутит рулетку чтобы разблокировать инструменты" },
  rickroll:     { name: "Rickroll",     rarity: "LEGENDARY", description: "Игрок вынужден будет смотреть видос в рандомных местах" },
  disco:        { name: "Disco",        rarity: "LEGENDARY", description: "Холст игрока периодически меняет цвета" },
  transparency: { name: "Transparency", rarity: "LEGENDARY", description: "Игрок вынужден поддерживать прозрачность рисунка" },
  brightness:   { name: "Brightness",   rarity: "LEGENDARY", description: "Расстояние курсора сверху и снизу влияет на яркость страницы" },
  roulette:     { name: "Roulette",     rarity: "LEGENDARY", description: "Игрок крутит рулетку пока не откроет доступ к холсту" },
  dvd:          { name: "Dvd",          rarity: "LEGENDARY", description: "Игрок вынужден рисовать с движущимся холстом" },
};

export const DEBUFF_RARITY_COLOR: Record<string, string> = {
  COMMON:    "#888",
  RARE:      "#4488ff",
  EPIC:      "#aa44ee",
  MYTHIC:    "#FF0606",
  LEGENDARY: "#ffcc00",
};
