# Generated by Django 5.2.6 on 2025-12-09 07:53

import django.db.models.deletion
import game.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('number', models.CharField(default=game.models.uniq_number, max_length=6)),
                ('max_players', models.IntegerField(default=12)),
                ('done', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
