# Generated by Django 6.0.6 on 2026-06-05 09:30

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='protections',
            field=models.JSONField(default=list, validators=[users.validators.validate_debuffs_list]),
        ),
        migrations.AlterField(
            model_name='cursor',
            name='debuffs',
            field=models.JSONField(default=list, validators=[users.validators.validate_debuffs_list]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только буквы, цифры, _ и -.', regex='^[a-zA-Z0-9_-]+$'), django.core.validators.MinLengthValidator(3, message='Имя пользователя должно содержать минимум 3 символа.'), django.core.validators.MaxLengthValidator(24, message='Имя пользователя не должно превышать 24 символа.')]),
        ),
    ]
