# Generated by Django 6.0.6 on 2026-06-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_canvas_protections_alter_cursor_debuffs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
