# Generated by Django 6.0.6 on 2026-06-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_canvas_rarity_cursor_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('mythic', 'Mythic'), ('legendary', 'Legendary')], default='common', max_length=10),
        ),
        migrations.AlterField(
            model_name='cursor',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('mythic', 'Mythic'), ('legendary', 'Legendary')], default='common', max_length=10),
        ),
    ]
