# Generated by Django 6.0.6 on 2026-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_canvas_rarity_alter_cursor_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='rarity',
            field=models.CharField(choices=[('null', 'Null'), ('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('mythic', 'Mythic'), ('legendary', 'Legendary')], default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='cursor',
            name='rarity',
            field=models.CharField(choices=[('null', 'Null'), ('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('mythic', 'Mythic'), ('legendary', 'Legendary')], default='null', max_length=10),
        ),
    ]
