# Generated by Django 6.0.6 on 2026-06-24 17:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_canvas_rarity_alter_cursor_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursor',
            name='image_orig',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cursor_image_orig'),
        ),
    ]
