# Generated by Django 6.0.6 on 2026-06-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_cursor_image_orig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursor',
            name='image_orig',
        ),
    ]
